"""Local Miso app: python3 server.py (http://127.0.0.1:8001)."""
import argparse
import gc
import io
import json
import math
import threading
import wave
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlsplit, parse_qs

from audio import decode_bytes
from voice_model import Voice_Model
from inspection import snapshot, trace_forward

ROOT = Path(__file__).resolve().parent
MODEL_PATH = ROOT / "model.json"
LABELS = ["Meow", "Woof", "Moo"]
INFERENCE_LOCK = threading.Lock()
MAX_BODY = 800_000

class ModelUnavailable(Exception):
    pass

def load_model(path=MODEL_PATH):
    """Read each time: training may publish a new checkpoint while we run."""
    try:
        saved = json.loads(Path(path).read_text())
        model = Voice_Model()
        params = model.parameters()
        weights = saved["weights"]
        if saved["labels"] != LABELS or len(weights) != len(params):
            raise ValueError("Checkpoint does not match the current model")
        if not all(type(w) in (float, int) and math.isfinite(w) for w in weights):
            raise ValueError("Invalid model weights")
        for param, weight in zip(params, weights):
            param.n = float(weight)
        return model
    except (OSError, ValueError, KeyError, TypeError) as error:
        raise ModelUnavailable("Model is not ready. Finish saving model.json, then try again.") from error

def validate_audio(payload):
    """Accept only one second of mono PCM16 WAV generated by the recorder."""
    try:
        with wave.open(io.BytesIO(payload), "rb") as audio:
            rate = audio.getframerate()
            if (audio.getnchannels() != 1 or audio.getsampwidth() != 2
                    or not 8000 <= rate <= 192000 or audio.getnframes() != rate
                    or len(audio.readframes(rate)) != rate * 2):
                raise ValueError("Expected one second of mono PCM16 WAV audio.")
    except (wave.Error, EOFError) as error:
        raise ValueError("Invalid WAV audio.") from error

def predict(payload, model_path=MODEL_PATH, inspect=False):
    validate_audio(payload)
    samples = decode_bytes(payload)  # Same PyAV resampling/padding as training.
    return predict_samples(samples, model_path, inspect)


def predict_samples(samples, model_path=MODEL_PATH, inspect=False):
    model = load_model(model_path)
    if len(samples) != 16000 or not all(math.isfinite(x) for x in samples):
        raise ValueError("Invalid audio samples.")
    # Use the actual training forward pass, including filter stride and scaling.
    if inspect:
        logits, trace = trace_forward(model, samples, LABELS)
    else:
        logits = [float(value.n) for value in model(samples)]
    if not all(math.isfinite(x) for x in logits):
        raise ModelUnavailable("Model returned invalid scores. Check the saved training weights.")
    # Match train.calculate_cross: exp(logit) / sum(exp(logits)).
    # This is softmax for display, not a training loss or temperature scaling.
    try:
        logits_exponentiated = [math.e ** logit for logit in logits]
        sum_exp = sum(logits_exponentiated)
        if not math.isfinite(sum_exp) or sum_exp == 0:
            raise ValueError("Unrepresentable exponential sum")
    except (OverflowError, ValueError) as error:
        raise ModelUnavailable("Raw softmax overflowed or underflowed. Check the saved model's output values.") from error
    probabilities = [value / sum_exp for value in logits_exponentiated]
    winner = max(range(3), key=probabilities.__getitem__)
    result = {"label": LABELS[winner], "probabilities": dict(zip(LABELS, probabilities))}
    if inspect:
        result["trace"] = trace
    return result


def example_files():
    folder = ROOT / "recordings"
    return {p.name: p for p in sorted(folder.glob('*.wav'))
            if p.is_file() and p.resolve().parent == folder.resolve() and p.stat().st_size <= 10_000_000}

class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT / "web"), **kwargs)

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        super().end_headers()

    def send_json(self, status, data):
        body = json.dumps(data, allow_nan=False).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = urlsplit(self.path).path
        if path == "/api/model":
            try:
                self.send_json(200, {"model": snapshot(load_model(), LABELS), "examples": list(example_files())})
            except ModelUnavailable as error:
                self.send_json(503, {"error": str(error)})
            return
        if path == "/api/health":
            try:
                load_model()
                self.send_json(200, {"ready": True, "labels": LABELS})
            except ModelUnavailable as error:
                self.send_json(503, {"ready": False, "error": str(error)})
            return
        # Explicit assets only: never serve checkpoints, recordings or source files.
        files = {"/": "web/index.html", "/index.html": "web/index.html",
                 "/fonts/fredoka.ttf": "web/fonts/fredoka.ttf",
                 "/fonts/bricolage-grotesque.ttf": "web/fonts/bricolage-grotesque.ttf",
                 "/fonts/departure-mono.woff2": "web/fonts/departure-mono.woff2",
                 "/app.css": "web/app.css", "/app.js": "web/app.js",
                 "/model": "web/model.html", "/model.css": "web/model.css", "/model.js": "web/model.js",
                 "/recorder-worklet.js": "web/recorder-worklet.js",
                 "/character/creature.svg": "character/creature.svg",
                 "/character/motion.css": "character/motion.css"}
        if path not in files:
            self.send_error(404)
            return
        asset = ROOT / files[path]
        body = asset.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", self.guess_type(str(asset)))
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_HEAD(self):
        self.send_error(405)

    def do_POST(self):
        path = urlsplit(self.path).path
        if path not in ("/api/predict", "/api/inspect-example"):
            self.send_json(404, {"error": "Not found."})
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            length = 0
        if not (1 if path == "/api/inspect-example" else 44) <= length <= (4096 if path == "/api/inspect-example" else MAX_BODY):
            self.send_json(413, {"error": "Send a one-second WAV recording."})
            return
        expected = "application/json" if path == "/api/inspect-example" else "audio/wav"
        if self.headers.get("Content-Type", "").split(";")[0] != expected:
            self.send_json(415, {"error": f"Expected {expected}."})
            return
        if not INFERENCE_LOCK.acquire(blocking=False):
            self.send_json(429, {"error": "Miso is still thinking. Try again in a moment."})
            return
        try:
            self.connection.settimeout(15)
            payload = self.rfile.read(length)
            if len(payload) != length:
                raise ValueError("Incomplete recording. Please try again.")
            if path == "/api/inspect-example":
                request = json.loads(payload)
                name = request.get("name") if isinstance(request, dict) else None
                example = example_files().get(name) if isinstance(name, str) else None
                if example is None:
                    raise ValueError("Unknown example")
                result = predict_samples(decode_bytes(example.read_bytes()), inspect=True)
                result["source"] = name
                self.send_json(200, result)
            else:
                inspect = parse_qs(urlsplit(self.path).query).get("inspect") == ["1"]
                self.send_json(200, predict(payload, inspect=inspect))
        except ModelUnavailable as error:
            self.send_json(503, {"error": str(error)})
        except (ValueError, EOFError):
            self.send_json(400, {"error": "Couldn't read that recording. Please try again."})
        except Exception as error:
            print(f"Prediction failed: {error}")
            self.send_json(500, {"error": "Prediction failed. Check the server terminal and try again."})
        finally:
            gc.collect()  # Release the training engine's temporary autograd graph.
            INFERENCE_LOCK.release()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8001)
    args = parser.parse_args()
    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    print(f"Miso is listening at http://127.0.0.1:{args.port}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
